apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-ml-deployment
spec:
  replicas: 2 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: fastapi-ml
  template:
    metadata:
      labels:
        app: fastapi-ml
    spec:
      containers:
      - name: fastapi-ml-container
        image: mindspaceai/new_app:v1
        ports:
        - containerPort: 80 # Streamlit's default port